package jframes;

import controlador.Reportes;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.plaf.DesktopPaneUI;
import modelo.UsuarioActual;

/**
 *
 * @author enmac
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public static JDesktopPane jDesktopPane_menu;

    public FrmMenuPrincipal() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setTitle("Menu Principal - Cowboy Cookies");
        this.setLocationRelativeTo(null);

        this.setLayout(null);
        jDesktopPane_menu = new controlador.FondoEscritorio();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);

        UsuarioActual.getTipo_usuario();
        // Controlar visibilidad del menú de usuarios
        if (!UsuarioActual.getTipo_usuario().equalsIgnoreCase("admin")) {
            MenuUsuarios.setVisible(false);
            MenuItem_GestionarUsuarios.setVisible(false); // ocultar si no es admin
            jMenuItem_GestionarProd.setVisible(false);
            jMenuItem_GestionarCat.setVisible(false);
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuUsuarios = new javax.swing.JMenu();
        MenuItem_GestionarUsuarios = new javax.swing.JMenuItem();
        MenuCategorias = new javax.swing.JMenu();
        jMenuItem_NuevaCat = new javax.swing.JMenuItem();
        jMenuItem_GestionarCat = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenu();
        jMenuItem_NuevoProducto = new javax.swing.JMenuItem();
        jMenuItem_GestionarProd = new javax.swing.JMenuItem();
        jMenuItem_ActStock = new javax.swing.JMenuItem();
        MenuFacturar = new javax.swing.JMenu();
        jMenuItem_nuevaVenta = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem_ReporteCat = new javax.swing.JMenuItem();
        jMenuItem_Reporteprod = new javax.swing.JMenuItem();
        jMenuItem_ReportesVentas = new javax.swing.JMenuItem();
        MenuLogout = new javax.swing.JMenu();
        jMenuItem_Cerrarsesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/usuario.png"))); // NOI18N
        MenuUsuarios.setText("Usuarios");
        MenuUsuarios.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N

        MenuItem_GestionarUsuarios.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        MenuItem_GestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/configuraciones.png"))); // NOI18N
        MenuItem_GestionarUsuarios.setText("Gestionar Usuarios");
        MenuItem_GestionarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuItem_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_GestionarUsuariosActionPerformed(evt);
            }
        });
        MenuUsuarios.add(MenuItem_GestionarUsuarios);

        jMenuBar1.add(MenuUsuarios);

        MenuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/categorias.png"))); // NOI18N
        MenuCategorias.setText("Categorias");
        MenuCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuCategorias.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        MenuCategorias.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem_NuevaCat.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_NuevaCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/agregar.png"))); // NOI18N
        jMenuItem_NuevaCat.setText("Nueva Categoria");
        jMenuItem_NuevaCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_NuevaCat.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_NuevaCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevaCatActionPerformed(evt);
            }
        });
        MenuCategorias.add(jMenuItem_NuevaCat);

        jMenuItem_GestionarCat.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_GestionarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/GestionarCategorias.png"))); // NOI18N
        jMenuItem_GestionarCat.setText("Gestionar Categorias");
        jMenuItem_GestionarCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_GestionarCat.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_GestionarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarCatActionPerformed(evt);
            }
        });
        MenuCategorias.add(jMenuItem_GestionarCat);

        jMenuBar1.add(MenuCategorias);

        MenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/producto.png"))); // NOI18N
        MenuProductos.setText("Productos");
        MenuProductos.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        MenuProductos.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem_NuevoProducto.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_NuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/nuevo-producto.png"))); // NOI18N
        jMenuItem_NuevoProducto.setText("Nuevo Producto");
        jMenuItem_NuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_NuevoProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_NuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevoProductoActionPerformed(evt);
            }
        });
        MenuProductos.add(jMenuItem_NuevoProducto);

        jMenuItem_GestionarProd.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_GestionarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/producto.png"))); // NOI18N
        jMenuItem_GestionarProd.setText("Gestionar Productos");
        jMenuItem_GestionarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_GestionarProd.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_GestionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarProdActionPerformed(evt);
            }
        });
        MenuProductos.add(jMenuItem_GestionarProd);

        jMenuItem_ActStock.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_ActStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/nuevo.png"))); // NOI18N
        jMenuItem_ActStock.setText("Actualizar Stock");
        jMenuItem_ActStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_ActStock.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_ActStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ActStockActionPerformed(evt);
            }
        });
        MenuProductos.add(jMenuItem_ActStock);

        jMenuBar1.add(MenuProductos);

        MenuFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/carrito.png"))); // NOI18N
        MenuFacturar.setText("Facturar");
        MenuFacturar.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        MenuFacturar.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem_nuevaVenta.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/anadir.png"))); // NOI18N
        jMenuItem_nuevaVenta.setText("Nueva Venta");
        jMenuItem_nuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_nuevaVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevaVentaActionPerformed(evt);
            }
        });
        MenuFacturar.add(jMenuItem_nuevaVenta);

        jMenuBar1.add(MenuFacturar);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/reportes.png"))); // NOI18N
        MenuReportes.setText("Reportes");
        MenuReportes.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        MenuReportes.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem_ReporteCat.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_ReporteCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/reporte1.png"))); // NOI18N
        jMenuItem_ReporteCat.setText("Reportes Categorias");
        jMenuItem_ReporteCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_ReporteCat.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_ReporteCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReporteCatActionPerformed(evt);
            }
        });
        MenuReportes.add(jMenuItem_ReporteCat);

        jMenuItem_Reporteprod.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_Reporteprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/reporte1.png"))); // NOI18N
        jMenuItem_Reporteprod.setText("Reportes Productos");
        jMenuItem_Reporteprod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_Reporteprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReporteprodActionPerformed(evt);
            }
        });
        MenuReportes.add(jMenuItem_Reporteprod);

        jMenuItem_ReportesVentas.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_ReportesVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/reporte1.png"))); // NOI18N
        jMenuItem_ReportesVentas.setText("Reportes Ventas");
        jMenuItem_ReportesVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_ReportesVentas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_ReportesVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReportesVentasActionPerformed(evt);
            }
        });
        MenuReportes.add(jMenuItem_ReportesVentas);

        jMenuBar1.add(MenuReportes);

        MenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/cerrar-sesion.png"))); // NOI18N
        MenuLogout.setText("Cerrar Sesión");
        MenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuLogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        MenuLogout.setPreferredSize(new java.awt.Dimension(200, 40));

        jMenuItem_Cerrarsesion.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItem_Cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/cerrar-sesion.png"))); // NOI18N
        jMenuItem_Cerrarsesion.setText("Cerrar sesión");
        jMenuItem_Cerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_Cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CerrarsesionActionPerformed(evt);
            }
        });
        MenuLogout.add(jMenuItem_Cerrarsesion);

        jMenuBar1.add(MenuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_CerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CerrarsesionActionPerformed
        jfLogin login = new jfLogin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CerrarsesionActionPerformed

    private void jMenuItem_NuevaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevaCatActionPerformed
        FrmNuevaCategoria FrmNuevaCategoria = new FrmNuevaCategoria();
        jDesktopPane_menu.add(FrmNuevaCategoria);
        FrmNuevaCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevaCatActionPerformed

    private void jMenuItem_GestionarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarCatActionPerformed
        FrmGestionarCategoria FrmGestionarCategoria = new FrmGestionarCategoria();
        jDesktopPane_menu.add(FrmGestionarCategoria);
        FrmGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarCatActionPerformed

    private void jMenuItem_NuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevoProductoActionPerformed
        FrmNuevoProducto FrmNuevoProducto = new FrmNuevoProducto();
        jDesktopPane_menu.add(FrmNuevoProducto);
        FrmNuevoProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevoProductoActionPerformed

    private void jMenuItem_GestionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarProdActionPerformed
        FrmGestionarProducto FrmGestionarProducto = new FrmGestionarProducto();
        jDesktopPane_menu.add(FrmGestionarProducto);
        FrmGestionarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarProdActionPerformed

    private void jMenuItem_ActStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ActStockActionPerformed
        FrmActualizarStock FrmActualizarStock = new FrmActualizarStock();
        jDesktopPane_menu.add(FrmActualizarStock);
        FrmActualizarStock.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ActStockActionPerformed

    private void jMenuItem_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevaVentaActionPerformed
        FrmNuevaVenta FrmNuevaVenta = new FrmNuevaVenta();
        jDesktopPane_menu.add(FrmNuevaVenta);
        FrmNuevaVenta.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nuevaVentaActionPerformed

    private void jMenuItem_ReporteCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReporteCatActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReportesCategorias();
    }//GEN-LAST:event_jMenuItem_ReporteCatActionPerformed

    private void jMenuItem_ReporteprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReporteprodActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReportesProductos();
    }//GEN-LAST:event_jMenuItem_ReporteprodActionPerformed

    private void jMenuItem_ReportesVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReportesVentasActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReportesVentas();
    }//GEN-LAST:event_jMenuItem_ReportesVentasActionPerformed

    private void MenuItem_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_GestionarUsuariosActionPerformed
        FrmGestionarUsuarios FrmGestionarUsuarios = new FrmGestionarUsuarios();
        jDesktopPane_menu.add(FrmGestionarUsuarios);
        FrmGestionarUsuarios.setVisible(true);
    }//GEN-LAST:event_MenuItem_GestionarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCategorias;
    private javax.swing.JMenu MenuFacturar;
    private javax.swing.JMenuItem MenuItem_GestionarUsuarios;
    private javax.swing.JMenu MenuLogout;
    private javax.swing.JMenu MenuProductos;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_ActStock;
    private javax.swing.JMenuItem jMenuItem_Cerrarsesion;
    private javax.swing.JMenuItem jMenuItem_GestionarCat;
    private javax.swing.JMenuItem jMenuItem_GestionarProd;
    private javax.swing.JMenuItem jMenuItem_NuevaCat;
    private javax.swing.JMenuItem jMenuItem_NuevoProducto;
    private javax.swing.JMenuItem jMenuItem_ReporteCat;
    private javax.swing.JMenuItem jMenuItem_Reporteprod;
    private javax.swing.JMenuItem jMenuItem_ReportesVentas;
    private javax.swing.JMenuItem jMenuItem_nuevaVenta;
    // End of variables declaration//GEN-END:variables

}
